using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace TrOCR.Controls;
public partial class AdvRichTextBox : UserControl, IDisposable
{
    public IContainer components;
    public RichTextBoxEx EditBox;
    public ToolStripDropDownButton ButtonFont;
    public ToolStripDropDownButton ButtonLang;
    public ToolStripDropDownButton mode;
    public ToolStripButton ButtonBold;
    public ToolStripButton ButtonCheck;
    public ToolStripButton ButtonClose;
    public ColorPicker ButtonColor;
    public ToolStripButton ButtonFence;
    public ToolStripButton ButtonFind;
    public ToolStripButton ButtonFull;
    public ToolStripButton toolStripButtonIndent;
    public ToolStripButton ButtonLeft;
    public ToolStripButton ButtonMerge;
    public ToolStripButton ButtonParagraph;
    public ToolStripButton toolStripButtonR_arow;
    public ToolStripButton ButtonSend;
    public ToolStripButton ButtonSpace;
    public ToolStripButton ButtonSplit;
    public ToolStripButton ButtonTrans;
    public ToolStripButton ButtonVoice;
    public ToolStripSeparator toolStripSeparatorAlign;
    public ToolStripSeparator toolStripSeparatorFont;
    public ToolStripSeparator toolStripSeparatorFormat;
    public ToolStripEx toolStripToolBar;
    public ToolStripButton ButtonTopmost;
    public ToolStripMenuItem ZhEn;
    public ToolStripMenuItem ZhJp;
    public ToolStripMenuItem ZhKo;
    private ToolStripMenuItem font黑体;
    private ToolStripMenuItem font楷体;
    private ToolStripMenuItem font宋体;
    private ToolStripMenuItem font微软雅黑;
    private ToolStripMenuItem font新罗马;
    private ToolStripMenuItem mode_顶置;
    private ToolStripMenuItem mode_合并;
    private ToolStripMenuItem mode_正常;
    private ToolStripButton ButtonNote;
    public void InitializeComponent( )
    {
        CheckForIllegalCrossThreadCalls = false;
        ComponentResourceManager componentResourceManager = new(typeof(AdvRichTextBox));
        font宋体 = new ToolStripMenuItem( );
        font楷体 = new ToolStripMenuItem( );
        font黑体 = new ToolStripMenuItem( );
        font微软雅黑 = new ToolStripMenuItem( );
        font新罗马 = new ToolStripMenuItem( );
        ZhJp = new ToolStripMenuItem( );
        ZhKo = new ToolStripMenuItem( );
        ZhEn = new ToolStripMenuItem( );
        mode_顶置 = new ToolStripMenuItem( );
        mode_正常 = new ToolStripMenuItem( );
        mode_合并 = new ToolStripMenuItem( );
        ButtonTopmost = new ToolStripButton( );
        ButtonLang = new ToolStripDropDownButton( );
        mode = new ToolStripDropDownButton( );
        ButtonFont = new ToolStripDropDownButton( );
        toolStripToolBar = new ToolStripEx( );
        ButtonClose = new ToolStripButton( );
        ButtonBold = new ToolStripButton( );
        ButtonParagraph = new ToolStripButton( );
        ButtonFind = new ToolStripButton( );
        ButtonColor = new ColorPicker( );
        toolStripSeparatorFont = new ToolStripSeparator( );
        ButtonFence = new ToolStripButton( );
        ButtonSplit = new ToolStripButton( );
        ButtonCheck = new ToolStripButton( );
        toolStripButtonIndent = new ToolStripButton( );
        toolStripSeparatorFormat = new ToolStripSeparator( );
        ButtonLeft = new ToolStripButton( );
        ButtonMerge = new ToolStripButton( );
        ButtonVoice = new ToolStripButton( );
        ButtonFull = new ToolStripButton( );
        toolStripSeparatorAlign = new ToolStripSeparator( );
        ButtonSpace = new ToolStripButton( );
        toolStripButtonR_arow = new ToolStripButton( );
        ButtonSend = new ToolStripButton( );
        ButtonTrans = new ToolStripButton( );
        ButtonNote = new ToolStripButton( );
        EditBox = new RichTextBoxEx( );
        toolStripToolBar.SuspendLayout( );
        SuspendLayout( );
        toolStripSeparatorFont.ForeColor = Color.White;
        toolStripToolBar.GripStyle = ToolStripGripStyle.Hidden;
        toolStripToolBar.Location = new Point(0, 0);
        toolStripToolBar.Name = "toolStripToolBar";
        toolStripToolBar.RenderMode = ToolStripRenderMode.System;
        toolStripToolBar.Size = new Size(600, 25);
        toolStripToolBar.TabIndex = 1;
        toolStripToolBar.Click += toolStripToolBar_Click;
        toolStripToolBar.Text = "Tool Bar";
        toolStripToolBar.BackColor = Color.White;
        toolStripToolBar.Renderer = new MenuItemRenderer( );
        ButtonBold.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonBold.Image = (Image) componentResourceManager.GetObject("toolStripButtonBold.Image");
        ButtonBold.ImageTransparentColor = Color.Magenta;
        ButtonBold.Name = "toolStripButtonBold";
        ButtonBold.Size = new Size(23, 22);
        ButtonBold.Text = "加粗";
        ButtonBold.Click += ButtonBoldClick;
        ButtonParagraph.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonParagraph.Image = (Image) componentResourceManager.GetObject("toolStripButtonParagraph.Image");
        ButtonParagraph.ImageTransparentColor = Color.Magenta;
        ButtonParagraph.Name = "toolStripButtonParagraph";
        ButtonParagraph.Size = new Size(23, 22);
        ButtonParagraph.Text = "依据位置自动分段\r\n仅支持搜狗接口\r\n适合段落识别\r\n图片越清晰越准确\r\n准确度98%以上";
        ButtonParagraph.Click += toolStripButtonParagraph_Click;
        ButtonParagraph.MouseDown += toolStripButtonParagraph_keydown;
        ButtonFind.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFind.Image = (Image) componentResourceManager.GetObject("toolStripButtonFind.Image");
        ButtonFind.ImageTransparentColor = Color.Magenta;
        ButtonFind.Name = "toolStripButtonFind";
        ButtonFind.Size = new Size(23, 22);
        ButtonFind.Text = "查找\\替换";
        ButtonFind.Click += ButtonFindClick;
        ButtonColor.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonColor.Image = (Image) componentResourceManager.GetObject("toolStripButtonColor.Image");
        ButtonColor.ImageTransparentColor = Color.Magenta;
        ButtonColor.Name = "toolStripButtonColor";
        ButtonColor.Size = new Size(23, 22);
        ButtonColor.Text = "字体颜色";
        ButtonColor.Click += ButtonColorClick;
        ButtonLeft.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonLeft.Image = (Image) componentResourceManager.GetObject("toolStripButtonLeft.Image");
        ButtonLeft.ImageTransparentColor = Color.Magenta;
        ButtonLeft.Name = "toolStripButtonLeft";
        ButtonLeft.Size = new Size(23, 22);
        ButtonLeft.Text = "左对齐";
        ButtonLeft.Click += ButtonLeftClick;
        ButtonMerge.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonMerge.Image = (Image) componentResourceManager.GetObject("toolStripButtonMerge.Image");
        ButtonMerge.ImageTransparentColor = Color.Magenta;
        ButtonMerge.Name = "toolStripButtonMerge";
        ButtonMerge.Size = new Size(23, 22);
        ButtonMerge.Text = "将文本合并成一段";
        ButtonMerge.Click += ButtonMergeClick;
        ButtonMerge.MouseDown += ButtonMergeKeyDown;
        ButtonVoice.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonVoice.Image = (Image) componentResourceManager.GetObject("toolStripButtonVoice.Image");
        ButtonVoice.ImageTransparentColor = Color.Magenta;
        ButtonVoice.Name = "toolStripButtonVoice";
        ButtonVoice.Size = new Size(23, 22);
        ButtonVoice.Text = "朗读";
        ButtonVoice.Click += toolStripButtonVoice_Click;
        ButtonFull.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFull.Image = (Image) componentResourceManager.GetObject("toolStripButtonFull.Image");
        ButtonFull.ImageTransparentColor = Color.Magenta;
        ButtonFull.Name = "toolStripButtonFull";
        ButtonFull.Size = new Size(23, 22);
        ButtonFull.Text = "两端对齐";
        ButtonFull.Click += ButtonFullClick;
        ButtonSpace.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSpace.Image = (Image) componentResourceManager.GetObject("toolStripButtonspace.Image");
        ButtonSpace.ImageTransparentColor = Color.Magenta;
        ButtonSpace.Name = "toolStripButtonLine";
        ButtonSpace.Size = new Size(23, 22);
        ButtonSpace.Text = "首行缩进";
        ButtonSpace.Click += toolStripButtonspace_Click;
        ButtonFence.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFence.Image = (Image) componentResourceManager.GetObject("toolStripButtonFence.Image");
        ButtonFence.ImageTransparentColor = Color.Magenta;
        ButtonFence.Name = "toolStripButtonformat";
        ButtonFence.Size = new Size(23, 22);
        ButtonFence.Text = "截图时自动分栏\r\n多选区时无效\r\n单击显示分栏示意图";
        ButtonFence.Click += ButtonFenceClick;
        ButtonFence.MouseDown += ButtonFenceKeydown;
        ButtonSend.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSend.Image = (Image) componentResourceManager.GetObject("toolStripButtonSend.Image");
        ButtonSend.ImageTransparentColor = Color.Magenta;
        ButtonSend.Name = "toolStripButtonSend";
        ButtonSend.Size = new Size(23, 22);
        ButtonSend.Text = "复制/发送";
        ButtonSend.Click += toolStripButtonSend_Click;
        ButtonSplit.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSplit.Image = (Image) componentResourceManager.GetObject("toolStripButtonSplit.Image");
        ButtonSplit.ImageTransparentColor = Color.Magenta;
        ButtonSplit.Name = "toolStripButtonSplit";
        ButtonSplit.Size = new Size(23, 22);
        ButtonSplit.Text = "按图片中的行进行拆分";
        ButtonSplit.Click += toolStripButtonSplit_Click;
        ButtonSplit.MouseDown += ButtonSplitKeyDown;
        ButtonCheck.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonCheck.Image = (Image) componentResourceManager.GetObject("toolStripButtoncheck.Image");
        ButtonCheck.ImageTransparentColor = Color.Magenta;
        ButtonCheck.Name = "toolStripButtoncheck";
        ButtonCheck.Size = new Size(23, 22);
        ButtonCheck.Text = "检查文本是否有错别字";
        ButtonCheck.Click += ButtonCheckClick;
        ButtonCheck.MouseDown += ButtonCheckKeyDown;
        ButtonTrans.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonTrans.Image = (Image) componentResourceManager.GetObject("toolStripButtonTrans.Image");
        ButtonTrans.ImageTransparentColor = Color.Magenta;
        ButtonTrans.Name = "toolStripButtonTrans";
        ButtonTrans.Size = new Size(23, 22);
        ButtonTrans.Text = "翻译";
        ButtonTrans.Click += toolStripButtonTrans_Click;
        ButtonTrans.MouseDown += toolStripButtontrans_keydown;
        ButtonNote.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonNote.Image = (Image) componentResourceManager.GetObject("toolStripButtonNote.Image");
        ButtonNote.ImageTransparentColor = Color.Magenta;
        ButtonNote.Name = "toolStripButtonTrans";
        ButtonNote.Size = new Size(23, 22);
        ButtonNote.Text = "记录窗体";
        ButtonNote.Click += ButtonNoteClick;
        ButtonClose.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonClose.Image = (Image) componentResourceManager.GetObject("toolStripButtonclose.Image");
        ButtonClose.ImageTransparentColor = Color.Magenta;
        ButtonClose.Name = "toolStripButtonclose";
        ButtonClose.Size = new Size(23, 22);
        ButtonClose.Text = "关闭";
        ButtonClose.Click += ButtonCloseClick;
        ButtonLang.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonLang.Image = (Image) componentResourceManager.GetObject("languagle.Image");
        ButtonLang.ImageTransparentColor = Color.Magenta;
        ButtonLang.Name = "toolStripButtonclose";
        ButtonLang.Size = new Size(23, 22);
        ButtonLang.Text = "选择翻译语言\r\n支持自动检测\r\n可以双向翻译";
        ZhEn.Text = "中⇆英";
        ZhEn.ForeColor = Color.Red;
        ZhEn.Click += ZhEnClick;
        ZhJp.Text = "中⇆日";
        ZhJp.ForeColor = Color.Black;
        ZhJp.Click += ZhJpClick;
        ZhKo.Text = "中⇆韩";
        ZhKo.ForeColor = Color.Black;
        ZhKo.Click += ZhKoClick;
        ButtonLang.DropDownItems.Add(ZhEn);
        ButtonLang.DropDownItems.Add(ZhJp);
        ButtonLang.DropDownItems.Add(ZhKo);
        ButtonLang.AutoSize = false;
        ((ToolStripDropDownMenu) ButtonLang.DropDown).ShowImageMargin = false;
        ButtonLang.DropDown.BackColor = Color.White;
        ButtonLang.DropDown.AutoSize = false;
        ButtonLang.DropDown.AutoSize = Helper.System.DpiFactor != 1f;
        ButtonLang.DropDown.Width = Convert.ToInt32(55f);
        ButtonLang.DropDown.Height = Convert.ToInt32(70f);
        ButtonLang.ShowDropDownArrow = false;
        ButtonTopmost.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonTopmost.Image = (Image) componentResourceManager.GetObject("mode.Image");
        ButtonTopmost.ImageTransparentColor = Color.Magenta;
        ButtonTopmost.Name = "toolStripButtonclose";
        ButtonTopmost.Size = new Size(23, 22);
        ButtonTopmost.Text = "顶置";
        ButtonTopmost.MouseDown += topmost_keydown;
        ButtonFont.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFont.Image = (Image) componentResourceManager.GetObject("Fontstyle.Image");
        ButtonFont.ImageTransparentColor = Color.Magenta;
        ButtonFont.Name = "toolStripButtonclose";
        ButtonFont.Size = new Size(23, 22);
        ButtonFont.Text = "字体";
        ButtonFont.AutoSize = false;
        ((ToolStripDropDownMenu) ButtonFont.DropDown).ShowImageMargin = false;
        ButtonFont.DropDown.BackColor = Color.White;
        ButtonFont.DropDown.AutoSize = false;
        ButtonFont.DropDown.AutoSize = Helper.System.DpiFactor != 1f;
        ButtonFont.DropDown.Width = Convert.ToInt32(123f);
        ButtonFont.DropDown.Height = Convert.ToInt32(115f);
        ButtonFont.ShowDropDownArrow = false;
        font宋体.Text = "宋体";
        font宋体.ForeColor = Color.Black;
        font宋体.Click += SetFont宋体;
        font黑体.Text = "黑体";
        font黑体.ForeColor = Color.Black;
        font黑体.Click += SetFont黑体;
        font楷体.Text = "楷体";
        font楷体.ForeColor = Color.Black;
        font楷体.Click += SetFont楷体;
        font微软雅黑.Text = "微软雅黑";
        font微软雅黑.ForeColor = Color.Black;
        font微软雅黑.Click += SetFont微软雅黑;
        font新罗马.Text = "Time New Roman";
        font新罗马.ForeColor = Color.Red;
        font新罗马.Click += SetFont新罗马;
        ButtonFont.DropDownItems.Add(font宋体);
        ButtonFont.DropDownItems.Add(font黑体);
        ButtonFont.DropDownItems.Add(font楷体);
        ButtonFont.DropDownItems.Add(font微软雅黑);
        ButtonFont.DropDownItems.Add(font新罗马);
        EditBox.Location = new Point(32, 13);
        EditBox.Name = "richTextBox1";
        EditBox.Size = new Size(603, 457);
        EditBox.TabIndex = 0;
        EditBox.DetectUrls = true;
        EditBox.HideSelection = false;
        EditBox.Text = "";
        EditBox.BorderStyle = BorderStyle.None;
        EditBox.Dock = DockStyle.Fill;
        EditBox.Multiline = true;
        EditBox.ScrollBars = RichTextBoxScrollBars.Vertical;
        EditBox.KeyDown += RichBoxKeyDown;
        EditBox.LinkClicked += RichBoxTextClicked;
        EditBox.MouseDown += RichBoxMouseDown;
        EditBox.AllowDrop = true;
        EditBox.DragEnter += Form1_DragEnter;
        EditBox.DragDrop += Form1_DragDrop;
        EditBox.SelectionAlignment = TextAlign.Justify;
        EditBox.Font = new Font("Times New Roman", 16f * Helper.System.DpiFactor, GraphicsUnit.Pixel);
        EditBox.LanguageOption = RichTextBoxLanguageOptions.UIFonts;
        EditBox.TextChanged += RichBoxTextChanged;
        EditBox.Cursor = Cursors.IBeam;
        IndentTwo(1);
        mode.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        ButtonLang.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        ButtonFont.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        AutoScaleMode = AutoScaleMode.None;
        Controls.Add(EditBox);
        Controls.Add(toolStripToolBar);
        Name = "richTextBox";
        base.Text = "richTextBox";
        Size = new Size(600, 300);
        toolStripToolBar.ResumeLayout(false);
        toolStripToolBar.PerformLayout( );
        ResumeLayout(false);
        PerformLayout( );
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose( );
        }
        base.Dispose(disposing);
    }
}
