using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace TrOCR.Controls;
public partial class AdvRichTextBox : UserControl, IDisposable
{
    public IContainer components;
    public RichTextBoxEx EditBox;
    public ToolStripDropDownButton Fontstyle;
    public ToolStripDropDownButton languagle;
    public ToolStripDropDownButton mode;
    public ToolStripButton toolStripButtonBold;
    public ToolStripButton toolStripButtoncheck;
    public ToolStripButton toolStripButtonclose;
    public ColorPicker toolStripButtonColor;
    public ToolStripButton toolStripButtonFence;
    public ToolStripButton toolStripButtonFind;
    public ToolStripButton toolStripButtonFull;
    public ToolStripButton toolStripButtonIndent;
    public ToolStripButton toolStripButtonLeft;
    public ToolStripButton toolStripButtonMerge;
    public ToolStripButton toolStripButtonParagraph;
    public ToolStripButton toolStripButtonR_arow;
    public ToolStripButton toolStripButtonSend;
    public ToolStripButton toolStripButtonspace;
    public ToolStripButton toolStripButtonSplit;
    public ToolStripButton toolStripButtonTrans;
    public ToolStripButton toolStripButtonVoice;
    public ToolStripSeparator toolStripSeparatorAlign;
    public ToolStripSeparator toolStripSeparatorFont;
    public ToolStripSeparator toolStripSeparatorFormat;
    public ToolStripEx toolStripToolBar;
    public ToolStripButton topmost;
    public ToolStripMenuItem zh_en;
    public ToolStripMenuItem zh_jp;
    public ToolStripMenuItem zh_ko;
    private ToolStripMenuItem font黑体;
    private ToolStripMenuItem font楷体;
    private ToolStripMenuItem font宋体;
    private ToolStripMenuItem font微软雅黑;
    private ToolStripMenuItem font新罗马;
    private ToolStripMenuItem mode_顶置;
    private ToolStripMenuItem mode_合并;
    private ToolStripMenuItem mode_正常;
    private ToolStripButton toolStripButtonNote;
    public void InitializeComponent( )
    {
        CheckForIllegalCrossThreadCalls = false;
        ComponentResourceManager componentResourceManager = new(typeof(AdvRichTextBox));
        font宋体 = new ToolStripMenuItem( );
        font楷体 = new ToolStripMenuItem( );
        font黑体 = new ToolStripMenuItem( );
        font微软雅黑 = new ToolStripMenuItem( );
        font新罗马 = new ToolStripMenuItem( );
        zh_jp = new ToolStripMenuItem( );
        zh_ko = new ToolStripMenuItem( );
        zh_en = new ToolStripMenuItem( );
        mode_顶置 = new ToolStripMenuItem( );
        mode_正常 = new ToolStripMenuItem( );
        mode_合并 = new ToolStripMenuItem( );
        topmost = new ToolStripButton( );
        languagle = new ToolStripDropDownButton( );
        mode = new ToolStripDropDownButton( );
        Fontstyle = new ToolStripDropDownButton( );
        toolStripToolBar = new ToolStripEx( );
        toolStripButtonclose = new ToolStripButton( );
        toolStripButtonBold = new ToolStripButton( );
        toolStripButtonParagraph = new ToolStripButton( );
        toolStripButtonFind = new ToolStripButton( );
        toolStripButtonColor = new ColorPicker( );
        toolStripSeparatorFont = new ToolStripSeparator( );
        toolStripButtonFence = new ToolStripButton( );
        toolStripButtonSplit = new ToolStripButton( );
        toolStripButtoncheck = new ToolStripButton( );
        toolStripButtonIndent = new ToolStripButton( );
        toolStripSeparatorFormat = new ToolStripSeparator( );
        toolStripButtonLeft = new ToolStripButton( );
        toolStripButtonMerge = new ToolStripButton( );
        toolStripButtonVoice = new ToolStripButton( );
        toolStripButtonFull = new ToolStripButton( );
        toolStripSeparatorAlign = new ToolStripSeparator( );
        toolStripButtonspace = new ToolStripButton( );
        toolStripButtonR_arow = new ToolStripButton( );
        toolStripButtonSend = new ToolStripButton( );
        toolStripButtonTrans = new ToolStripButton( );
        toolStripButtonNote = new ToolStripButton( );
        EditBox = new RichTextBoxEx( );
        toolStripToolBar.SuspendLayout( );
        SuspendLayout( );
        toolStripSeparatorFont.ForeColor = Color.White;
        toolStripToolBar.GripStyle = ToolStripGripStyle.Hidden;
        toolStripToolBar.Location = new Point(0, 0);
        toolStripToolBar.Name = "toolStripToolBar";
        toolStripToolBar.RenderMode = ToolStripRenderMode.System;
        toolStripToolBar.Size = new Size(600, 25);
        toolStripToolBar.TabIndex = 1;
        toolStripToolBar.Click += toolStripToolBar_Click;
        toolStripToolBar.Text = "Tool Bar";
        toolStripToolBar.BackColor = Color.White;
        toolStripToolBar.Renderer = new MenuItemRenderer( );
        toolStripButtonBold.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonBold.Image = (Image) componentResourceManager.GetObject("toolStripButtonBold.Image");
        toolStripButtonBold.ImageTransparentColor = Color.Magenta;
        toolStripButtonBold.Name = "toolStripButtonBold";
        toolStripButtonBold.Size = new Size(23, 22);
        toolStripButtonBold.Text = "加粗";
        toolStripButtonBold.Click += ButtonBoldClick;
        toolStripButtonParagraph.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonParagraph.Image = (Image) componentResourceManager.GetObject("toolStripButtonParagraph.Image");
        toolStripButtonParagraph.ImageTransparentColor = Color.Magenta;
        toolStripButtonParagraph.Name = "toolStripButtonParagraph";
        toolStripButtonParagraph.Size = new Size(23, 22);
        toolStripButtonParagraph.Text = "依据位置自动分段\r\n仅支持搜狗接口\r\n适合段落识别\r\n图片越清晰越准确\r\n准确度98%以上";
        toolStripButtonParagraph.Click += toolStripButtonParagraph_Click;
        toolStripButtonParagraph.MouseDown += toolStripButtonParagraph_keydown;
        toolStripButtonFind.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonFind.Image = (Image) componentResourceManager.GetObject("toolStripButtonFind.Image");
        toolStripButtonFind.ImageTransparentColor = Color.Magenta;
        toolStripButtonFind.Name = "toolStripButtonFind";
        toolStripButtonFind.Size = new Size(23, 22);
        toolStripButtonFind.Text = "查找\\替换";
        toolStripButtonFind.Click += toolStripButtonFind_Click;
        toolStripButtonColor.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonColor.Image = (Image) componentResourceManager.GetObject("toolStripButtonColor.Image");
        toolStripButtonColor.ImageTransparentColor = Color.Magenta;
        toolStripButtonColor.Name = "toolStripButtonColor";
        toolStripButtonColor.Size = new Size(23, 22);
        toolStripButtonColor.Text = "字体颜色";
        toolStripButtonColor.Click += ButtonColorClick;
        toolStripButtonLeft.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonLeft.Image = (Image) componentResourceManager.GetObject("toolStripButtonLeft.Image");
        toolStripButtonLeft.ImageTransparentColor = Color.Magenta;
        toolStripButtonLeft.Name = "toolStripButtonLeft";
        toolStripButtonLeft.Size = new Size(23, 22);
        toolStripButtonLeft.Text = "左对齐";
        toolStripButtonLeft.Click += toolStripButtonLeft_Click;
        toolStripButtonMerge.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonMerge.Image = (Image) componentResourceManager.GetObject("toolStripButtonMerge.Image");
        toolStripButtonMerge.ImageTransparentColor = Color.Magenta;
        toolStripButtonMerge.Name = "toolStripButtonMerge";
        toolStripButtonMerge.Size = new Size(23, 22);
        toolStripButtonMerge.Text = "将文本合并成一段";
        toolStripButtonMerge.Click += toolStripButtonMerge_Click;
        toolStripButtonMerge.MouseDown += toolStripButtonMerge_keydown;
        toolStripButtonVoice.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonVoice.Image = (Image) componentResourceManager.GetObject("toolStripButtonVoice.Image");
        toolStripButtonVoice.ImageTransparentColor = Color.Magenta;
        toolStripButtonVoice.Name = "toolStripButtonVoice";
        toolStripButtonVoice.Size = new Size(23, 22);
        toolStripButtonVoice.Text = "朗读";
        toolStripButtonVoice.Click += toolStripButtonVoice_Click;
        toolStripButtonFull.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonFull.Image = (Image) componentResourceManager.GetObject("toolStripButtonFull.Image");
        toolStripButtonFull.ImageTransparentColor = Color.Magenta;
        toolStripButtonFull.Name = "toolStripButtonFull";
        toolStripButtonFull.Size = new Size(23, 22);
        toolStripButtonFull.Text = "两端对齐";
        toolStripButtonFull.Click += ButtonFullClick;
        toolStripButtonspace.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonspace.Image = (Image) componentResourceManager.GetObject("toolStripButtonspace.Image");
        toolStripButtonspace.ImageTransparentColor = Color.Magenta;
        toolStripButtonspace.Name = "toolStripButtonLine";
        toolStripButtonspace.Size = new Size(23, 22);
        toolStripButtonspace.Text = "首行缩进";
        toolStripButtonspace.Click += toolStripButtonspace_Click;
        toolStripButtonFence.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonFence.Image = (Image) componentResourceManager.GetObject("toolStripButtonFence.Image");
        toolStripButtonFence.ImageTransparentColor = Color.Magenta;
        toolStripButtonFence.Name = "toolStripButtonformat";
        toolStripButtonFence.Size = new Size(23, 22);
        toolStripButtonFence.Text = "截图时自动分栏\r\n多选区时无效\r\n单击显示分栏示意图";
        toolStripButtonFence.Click += ButtonFenceClick;
        toolStripButtonFence.MouseDown += ButtonFenceKeydown;
        toolStripButtonSend.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonSend.Image = (Image) componentResourceManager.GetObject("toolStripButtonSend.Image");
        toolStripButtonSend.ImageTransparentColor = Color.Magenta;
        toolStripButtonSend.Name = "toolStripButtonSend";
        toolStripButtonSend.Size = new Size(23, 22);
        toolStripButtonSend.Text = "复制/发送";
        toolStripButtonSend.Click += toolStripButtonSend_Click;
        toolStripButtonSplit.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonSplit.Image = (Image) componentResourceManager.GetObject("toolStripButtonSplit.Image");
        toolStripButtonSplit.ImageTransparentColor = Color.Magenta;
        toolStripButtonSplit.Name = "toolStripButtonSplit";
        toolStripButtonSplit.Size = new Size(23, 22);
        toolStripButtonSplit.Text = "按图片中的行进行拆分";
        toolStripButtonSplit.Click += toolStripButtonSplit_Click;
        toolStripButtonSplit.MouseDown += toolStripButtonSplit_keydown;
        toolStripButtoncheck.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtoncheck.Image = (Image) componentResourceManager.GetObject("toolStripButtoncheck.Image");
        toolStripButtoncheck.ImageTransparentColor = Color.Magenta;
        toolStripButtoncheck.Name = "toolStripButtoncheck";
        toolStripButtoncheck.Size = new Size(23, 22);
        toolStripButtoncheck.Text = "检查文本是否有错别字";
        toolStripButtoncheck.Click += ButtonCheckClick;
        toolStripButtoncheck.MouseDown += ButtonCheckKeyDown;
        toolStripButtonTrans.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonTrans.Image = (Image) componentResourceManager.GetObject("toolStripButtonTrans.Image");
        toolStripButtonTrans.ImageTransparentColor = Color.Magenta;
        toolStripButtonTrans.Name = "toolStripButtonTrans";
        toolStripButtonTrans.Size = new Size(23, 22);
        toolStripButtonTrans.Text = "翻译";
        toolStripButtonTrans.Click += toolStripButtonTrans_Click;
        toolStripButtonTrans.MouseDown += toolStripButtontrans_keydown;
        toolStripButtonNote.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonNote.Image = (Image) componentResourceManager.GetObject("toolStripButtonNote.Image");
        toolStripButtonNote.ImageTransparentColor = Color.Magenta;
        toolStripButtonNote.Name = "toolStripButtonTrans";
        toolStripButtonNote.Size = new Size(23, 22);
        toolStripButtonNote.Text = "记录窗体";
        toolStripButtonNote.Click += toolStripButtonNote_Click;
        toolStripButtonclose.DisplayStyle = ToolStripItemDisplayStyle.Image;
        toolStripButtonclose.Image = (Image) componentResourceManager.GetObject("toolStripButtonclose.Image");
        toolStripButtonclose.ImageTransparentColor = Color.Magenta;
        toolStripButtonclose.Name = "toolStripButtonclose";
        toolStripButtonclose.Size = new Size(23, 22);
        toolStripButtonclose.Text = "关闭";
        toolStripButtonclose.Click += ButtonCloseClick;
        languagle.DisplayStyle = ToolStripItemDisplayStyle.Image;
        languagle.Image = (Image) componentResourceManager.GetObject("languagle.Image");
        languagle.ImageTransparentColor = Color.Magenta;
        languagle.Name = "toolStripButtonclose";
        languagle.Size = new Size(23, 22);
        languagle.Text = "选择翻译语言\r\n支持自动检测\r\n可以双向翻译";
        zh_en.Text = "中⇆英";
        zh_en.ForeColor = Color.Red;
        zh_en.Click += zh_en_Click;
        zh_jp.Text = "中⇆日";
        zh_jp.ForeColor = Color.Black;
        zh_jp.Click += zh_jp_Click;
        zh_ko.Text = "中⇆韩";
        zh_ko.ForeColor = Color.Black;
        zh_ko.Click += zh_ko_Click;
        languagle.DropDownItems.Add(zh_en);
        languagle.DropDownItems.Add(zh_jp);
        languagle.DropDownItems.Add(zh_ko);
        languagle.AutoSize = false;
        ((ToolStripDropDownMenu) languagle.DropDown).ShowImageMargin = false;
        languagle.DropDown.BackColor = Color.White;
        languagle.DropDown.AutoSize = false;
        languagle.DropDown.AutoSize = Helper.System.DpiFactor != 1f;
        languagle.DropDown.Width = Convert.ToInt32(55f);
        languagle.DropDown.Height = Convert.ToInt32(70f);
        languagle.ShowDropDownArrow = false;
        topmost.DisplayStyle = ToolStripItemDisplayStyle.Image;
        topmost.Image = (Image) componentResourceManager.GetObject("mode.Image");
        topmost.ImageTransparentColor = Color.Magenta;
        topmost.Name = "toolStripButtonclose";
        topmost.Size = new Size(23, 22);
        topmost.Text = "顶置";
        topmost.MouseDown += topmost_keydown;
        Fontstyle.DisplayStyle = ToolStripItemDisplayStyle.Image;
        Fontstyle.Image = (Image) componentResourceManager.GetObject("Fontstyle.Image");
        Fontstyle.ImageTransparentColor = Color.Magenta;
        Fontstyle.Name = "toolStripButtonclose";
        Fontstyle.Size = new Size(23, 22);
        Fontstyle.Text = "字体";
        Fontstyle.AutoSize = false;
        ((ToolStripDropDownMenu) Fontstyle.DropDown).ShowImageMargin = false;
        Fontstyle.DropDown.BackColor = Color.White;
        Fontstyle.DropDown.AutoSize = false;
        Fontstyle.DropDown.AutoSize = Helper.System.DpiFactor != 1f;
        Fontstyle.DropDown.Width = Convert.ToInt32(123f);
        Fontstyle.DropDown.Height = Convert.ToInt32(115f);
        Fontstyle.ShowDropDownArrow = false;
        font宋体.Text = "宋体";
        font宋体.ForeColor = Color.Black;
        font宋体.Click += SetFont宋体;
        font黑体.Text = "黑体";
        font黑体.ForeColor = Color.Black;
        font黑体.Click += SetFont黑体;
        font楷体.Text = "楷体";
        font楷体.ForeColor = Color.Black;
        font楷体.Click += SetFont楷体;
        font微软雅黑.Text = "微软雅黑";
        font微软雅黑.ForeColor = Color.Black;
        font微软雅黑.Click += SetFont微软雅黑;
        font新罗马.Text = "Time New Roman";
        font新罗马.ForeColor = Color.Red;
        font新罗马.Click += SetFont新罗马;
        Fontstyle.DropDownItems.Add(font宋体);
        Fontstyle.DropDownItems.Add(font黑体);
        Fontstyle.DropDownItems.Add(font楷体);
        Fontstyle.DropDownItems.Add(font微软雅黑);
        Fontstyle.DropDownItems.Add(font新罗马);
        EditBox.Location = new Point(32, 13);
        EditBox.Name = "richTextBox1";
        EditBox.Size = new Size(603, 457);
        EditBox.TabIndex = 0;
        EditBox.DetectUrls = true;
        EditBox.HideSelection = false;
        EditBox.Text = "";
        EditBox.BorderStyle = BorderStyle.None;
        EditBox.Dock = DockStyle.Fill;
        EditBox.Multiline = true;
        EditBox.ScrollBars = RichTextBoxScrollBars.Vertical;
        EditBox.KeyDown += richTextBox1_KeyDown;
        EditBox.LinkClicked += richTextBox1_LinkClicked;
        EditBox.MouseDown += RichBoxMouseDown;
        EditBox.AllowDrop = true;
        EditBox.MouseEnter += Form1_MouseEnter;
        EditBox.DragEnter += Form1_DragEnter;
        EditBox.DragDrop += Form1_DragDrop;
        EditBox.SelectionAlignment = TextAlign.Justify;
        EditBox.Font = new Font("Times New Roman", 16f * Helper.System.DpiFactor, GraphicsUnit.Pixel);
        EditBox.LanguageOption = RichTextBoxLanguageOptions.UIFonts;
        EditBox.TextChanged += richeditbox_TextChanged;
        EditBox.Cursor = Cursors.IBeam;
        IndentTwo(1);
        mode.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        languagle.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        Fontstyle.Font = new Font("微软雅黑", 9f * Helper.System.DpiFactor, FontStyle.Regular);
        AutoScaleMode = AutoScaleMode.None;
        Controls.Add(EditBox);
        Controls.Add(toolStripToolBar);
        Name = "richTextBox";
        base.Text = "richTextBox";
        Size = new Size(600, 300);
        toolStripToolBar.ResumeLayout(false);
        toolStripToolBar.PerformLayout( );
        ResumeLayout(false);
        PerformLayout( );
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose( );
        }
        base.Dispose(disposing);
    }
}
