using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace TrOCR.Controls;
public partial class AdvRichTextBox : UserControl, IDisposable
{
    private IContainer components;
    public RichTextBoxEx EditBox;
    private ToolStripDropDownButton ButtonFont;
    private ToolStripDropDownButton ButtonLang;
    private ToolStripDropDownButton mode;
    private ToolStripButton ButtonBold;
    private ToolStripButton ButtonCheck;
    private ToolStripButton ButtonTransClose;
    private ColorPicker ButtonColor;
    private ToolStripButton ButtonFence;
    private ToolStripButton ButtonFind;
    private ToolStripButton ButtonFull;
    private ToolStripButton ButtonIndent;
    private ToolStripButton ButtonLeft;
    private ToolStripButton ButtonMerge;
    private ToolStripButton ButtonParagraph;
    private ToolStripButton ButtonR_arow;
    private ToolStripButton ButtonSend;
    private ToolStripButton ButtonSpace;
    private ToolStripButton ButtonSplit;
    private ToolStripButton ButtonTrans;
    private ToolStripButton ButtonVoice;
    private ToolStripSeparator toolStripSeparatorAlign;
    private ToolStripSeparator toolStripSeparatorFont;
    private ToolStripSeparator toolStripSeparatorFormat;
    private ToolStripEx toolStripToolBar;
    private ToolStripButton ButtonTopmost;
    private ToolStripMenuItem ZhEn;
    private ToolStripMenuItem ZhJp;
    private ToolStripMenuItem ZhKo;
    private ToolStripMenuItem font黑体;
    private ToolStripMenuItem font楷体;
    private ToolStripMenuItem font宋体;
    private ToolStripMenuItem font微软雅黑;
    private ToolStripMenuItem font新罗马;
    private ToolStripMenuItem mode_顶置;
    private ToolStripMenuItem mode_合并;
    private ToolStripMenuItem mode_正常;
    private ToolStripButton ButtonNote;


    public void InitializeComponent( )
    {
        AutoScaleMode = AutoScaleMode.None;
        EditBox = new RichTextBoxEx( );
        EditBox.AllowDrop = true;
        EditBox.BorderStyle = BorderStyle.None;
        EditBox.Cursor = Cursors.IBeam;
        EditBox.DetectUrls = true;
        EditBox.Dock = DockStyle.Fill;
        EditBox.DragDrop += FormDragDrop;
        EditBox.DragEnter += FormDragEnter;
        EditBox.HideSelection = false;
        EditBox.KeyDown += RichBoxKeyDown;
        EditBox.LanguageOption = RichTextBoxLanguageOptions.UIFonts;
        EditBox.LinkClicked += RichBoxTextClicked;
        EditBox.Location = new Point(32, 13);
        EditBox.MouseDown += RichBoxMouseDown;
        EditBox.Multiline = true;
        EditBox.Name = "richTextBox1";
        EditBox.ScrollBars = RichTextBoxScrollBars.Vertical;
        EditBox.SelectionAlignment = TextAlign.Justify;
        EditBox.Size = new Size(603, 457);
        EditBox.TabIndex = 0;
        EditBox.Text = "";
        EditBox.TextChanged += RichBoxTextChanged;
        font黑体 = new ToolStripMenuItem( );
        font黑体.Click += SetFont黑体;
        font黑体.ForeColor = Color.Black;
        font黑体.Text = "黑体";
        font楷体 = new ToolStripMenuItem( );
        font楷体.Click += SetFont楷体;
        font楷体.ForeColor = Color.Black;
        font楷体.Text = "楷体";
        font宋体 = new ToolStripMenuItem( );
        font宋体.Click += SetFont宋体;
        font宋体.ForeColor = Color.Black;
        font宋体.Text = "宋体";
        font微软雅黑 = new ToolStripMenuItem( );
        font微软雅黑.Click += SetFont微软雅黑;
        font微软雅黑.ForeColor = Color.Black;
        font微软雅黑.Text = "微软雅黑";
        font新罗马 = new ToolStripMenuItem( );
        font新罗马.Click += SetFont新罗马;
        font新罗马.ForeColor = Color.Red;
        font新罗马.Text = "Time New Roman";
        mode = new ToolStripDropDownButton( );
        mode_顶置 = new ToolStripMenuItem( );
        mode_合并 = new ToolStripMenuItem( );
        mode_正常 = new ToolStripMenuItem( );
        ZhEn = new ToolStripMenuItem( );
        ZhEn.Click += ZhEnClick;
        ZhEn.ForeColor = Color.Red;
        ZhEn.Text = "中⇆英";
        ZhJp = new ToolStripMenuItem( );
        ZhJp.Click += ZhJpClick;
        ZhJp.ForeColor = Color.Black;
        ZhJp.Text = "中⇆日";
        ZhKo = new ToolStripMenuItem( );
        ZhKo.Click += ZhKoClick;
        ZhKo.ForeColor = Color.Black;
        ZhKo.Text = "中⇆韩";
        ButtonBold = new ToolStripButton( );
        ButtonBold.Click += ButtonBoldClick;
        ButtonBold.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonBold.Image = (Image) resourceManager.GetObject("ButtonBold.Image");
        ButtonBold.ImageTransparentColor = Color.Magenta;
        ButtonBold.Name = "ButtonBold";
        ButtonBold.Size = new Size(23, 22);
        ButtonBold.Text = "加粗";
        ButtonCheck = new ToolStripButton( );
        ButtonCheck.Click += ButtonCheckClick;
        ButtonCheck.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonCheck.Image = (Image) resourceManager.GetObject("Buttoncheck.Image");
        ButtonCheck.ImageTransparentColor = Color.Magenta;
        ButtonCheck.MouseDown += ButtonCheckRightClick;
        ButtonCheck.Name = "Buttoncheck";
        ButtonCheck.Size = new Size(23, 22);
        ButtonCheck.Text = "检查文本是否有错别字";
        ButtonTransClose = new ToolStripButton( );
        ButtonTransClose.Click += ButtonTransCloseClick;
        ButtonTransClose.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonTransClose.Image = (Image) resourceManager.GetObject("Buttonclose.Image");
        ButtonTransClose.ImageTransparentColor = Color.Magenta;
        ButtonTransClose.Name = "Buttonclose";
        ButtonTransClose.Size = new Size(23, 22);
        ButtonTransClose.Text = "关闭";
        ButtonColor = new ColorPicker( );
        ButtonColor.Click += ButtonColorClick;
        ButtonColor.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonColor.Image = (Image) resourceManager.GetObject("ButtonColor.Image");
        ButtonColor.ImageTransparentColor = Color.Magenta;
        ButtonColor.Name = "ButtonColor";
        ButtonColor.Size = new Size(23, 22);
        ButtonColor.Text = "字体颜色";
        ButtonFence = new ToolStripButton( );
        ButtonFence.Click += ButtonFenceClick;
        ButtonFence.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFence.Image = (Image) resourceManager.GetObject("ButtonFence.Image");
        ButtonFence.ImageTransparentColor = Color.Magenta;
        ButtonFence.Name = "Buttonformat";
        ButtonFence.Size = new Size(23, 22);
        ButtonFence.Text = "截图时自动分栏\r\n多选区时无效";
        ButtonFind = new ToolStripButton( );
        ButtonFind.Click += ButtonFindClick;
        ButtonFind.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFind.Image = (Image) resourceManager.GetObject("ButtonFind.Image");
        ButtonFind.ImageTransparentColor = Color.Magenta;
        ButtonFind.Name = "ButtonFind";
        ButtonFind.Size = new Size(23, 22);
        ButtonFind.Text = "查找\\替换";
        ButtonFont = new ToolStripDropDownButton( );
        ButtonFont.AutoSize = false;
        ButtonFont.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFont.DropDown.AutoSize = true;
        ButtonFont.DropDown.BackColor = Color.White;
        ButtonFont.DropDown.Height = Convert.ToInt32(115f);
        ButtonFont.DropDown.Width = Convert.ToInt32(123f);
        ButtonFont.DropDownItems.Add(font黑体);
        ButtonFont.DropDownItems.Add(font楷体);
        ButtonFont.DropDownItems.Add(font宋体);
        ButtonFont.DropDownItems.Add(font微软雅黑);
        ButtonFont.DropDownItems.Add(font新罗马);
        ButtonFont.Image = (Image) resourceManager.GetObject("Fontstyle.Image");
        ButtonFont.ImageTransparentColor = Color.Magenta;
        ButtonFont.Name = "Buttonclose";
        ButtonFont.ShowDropDownArrow = false;
        ButtonFont.Size = new Size(23, 22);
        ButtonFont.Text = "字体";
        ButtonFull = new ToolStripButton( );
        ButtonFull.Click += ButtonFullClick;
        ButtonFull.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonFull.Image = (Image) resourceManager.GetObject("ButtonFull.Image");
        ButtonFull.ImageTransparentColor = Color.Magenta;
        ButtonFull.Name = "ButtonFull";
        ButtonFull.Size = new Size(23, 22);
        ButtonFull.Text = "两端对齐";
        ButtonLang = new ToolStripDropDownButton( );
        ButtonLang.AutoSize = false;
        ButtonLang.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonLang.DropDown.AutoSize = true;
        ButtonLang.DropDown.BackColor = Color.White;
        ButtonLang.DropDown.Height = Convert.ToInt32(70f);
        ButtonLang.DropDown.Width = Convert.ToInt32(55f);
        ButtonLang.DropDownItems.Add(ZhEn);
        ButtonLang.DropDownItems.Add(ZhJp);
        ButtonLang.DropDownItems.Add(ZhKo);
        ButtonLang.Image = (Image) resourceManager.GetObject("language.Image");
        ButtonLang.ImageTransparentColor = Color.Magenta;
        ButtonLang.Name = "Buttonclose";
        ButtonLang.ShowDropDownArrow = false;
        ButtonLang.Size = new Size(23, 22);
        ButtonLang.Text = "选择翻译语言\r\n支持自动检测\r\n可以双向翻译";
        ButtonLeft = new ToolStripButton( );
        ButtonLeft.Click += ButtonLeftClick;
        ButtonLeft.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonLeft.Image = (Image) resourceManager.GetObject("ButtonLeft.Image");
        ButtonLeft.ImageTransparentColor = Color.Magenta;
        ButtonLeft.Name = "ButtonLeft";
        ButtonLeft.Size = new Size(23, 22);
        ButtonLeft.Text = "左对齐";
        ButtonMerge = new ToolStripButton( );
        ButtonMerge.Click += ButtonMergeClick;
        ButtonMerge.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonMerge.Image = (Image) resourceManager.GetObject("ButtonMerge.Image");
        ButtonMerge.ImageTransparentColor = Color.Magenta;
        ButtonMerge.Name = "ButtonMerge";
        ButtonMerge.Size = new Size(23, 22);
        ButtonMerge.Text = "将文本合并成一段";
        ButtonNote = new ToolStripButton( );
        ButtonNote.Click += ButtonNoteClick;
        ButtonNote.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonNote.Image = (Image) resourceManager.GetObject("ButtonNote.Image");
        ButtonNote.ImageTransparentColor = Color.Magenta;
        ButtonNote.Name = "ButtonTrans";
        ButtonNote.Size = new Size(23, 22);
        ButtonNote.Text = "记录窗体";
        ButtonParagraph = new ToolStripButton( );
        ButtonParagraph.Click += ButtonParagraphClick;
        ButtonParagraph.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonParagraph.Image = (Image) resourceManager.GetObject("ButtonParagraph.Image");
        ButtonParagraph.ImageTransparentColor = Color.Magenta;
        ButtonParagraph.Name = "ButtonParagraph";
        ButtonParagraph.Size = new Size(23, 22);
        ButtonParagraph.Text = "依据位置自动分段\r\n仅支持搜狗接口\r\n适合段落识别\r\n图片越清晰越准确\r\n准确度98%以上";
        ButtonSend = new ToolStripButton( );
        ButtonSend.Click += ButtonSendClick;
        ButtonSend.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSend.Image = (Image) resourceManager.GetObject("ButtonSend.Image");
        ButtonSend.ImageTransparentColor = Color.Magenta;
        ButtonSend.Name = "ButtonSend";
        ButtonSend.Size = new Size(23, 22);
        ButtonSend.Text = "复制/发送";
        ButtonSpace = new ToolStripButton( );
        ButtonSpace.Click += ButtonSpaceClick;
        ButtonSpace.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSpace.Image = (Image) resourceManager.GetObject("Buttonspace.Image");
        ButtonSpace.ImageTransparentColor = Color.Magenta;
        ButtonSpace.Name = "ButtonLine";
        ButtonSpace.Size = new Size(23, 22);
        ButtonSpace.Text = "首行缩进";
        ButtonSplit = new ToolStripButton( );
        ButtonSplit.Click += ButtonSplitClick;
        ButtonSplit.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonSplit.Image = (Image) resourceManager.GetObject("ButtonSplit.Image");
        ButtonSplit.ImageTransparentColor = Color.Magenta;
        ButtonSplit.Name = "ButtonSplit";
        ButtonSplit.Size = new Size(23, 22);
        ButtonSplit.Text = "按图片中的行进行拆分";
        ButtonTopmost = new ToolStripButton( );
        ButtonTopmost.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonTopmost.Image = (Image) resourceManager.GetObject("mode.Image");
        ButtonTopmost.ImageTransparentColor = Color.Magenta;
        ButtonTopmost.MouseDown += ButtomTopmostClick;
        ButtonTopmost.Name = "Buttonclose";
        ButtonTopmost.Size = new Size(23, 22);
        ButtonTopmost.Text = "顶置";
        ButtonTrans = new ToolStripButton( );
        ButtonTrans.Click += ButtonTransClick;
        ButtonTrans.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonTrans.Image = (Image) resourceManager.GetObject("ButtonTrans.Image");
        ButtonTrans.ImageTransparentColor = Color.Magenta;
        ButtonTrans.Name = "ButtonTrans";
        ButtonTrans.Size = new Size(23, 22);
        ButtonTrans.Text = "翻译";
        ButtonVoice = new ToolStripButton( );
        ButtonVoice.Click += ButtonVoiceClick;
        ButtonVoice.DisplayStyle = ToolStripItemDisplayStyle.Image;
        ButtonVoice.Image = (Image) resourceManager.GetObject("ButtonVoice.Image");
        ButtonVoice.ImageTransparentColor = Color.Magenta;
        ButtonVoice.Name = "ButtonVoice";
        ButtonVoice.Size = new Size(23, 22);
        ButtonVoice.Text = "朗读";
        Name = "richTextBox";
        Size = new Size(600, 300);
        ButtonIndent = new ToolStripButton( );
        ButtonR_arow = new ToolStripButton( );
        toolStripSeparatorAlign = new ToolStripSeparator( );
        toolStripSeparatorFont = new ToolStripSeparator( );
        toolStripSeparatorFont.ForeColor = Color.White;
        toolStripSeparatorFormat = new ToolStripSeparator( );
        toolStripToolBar = new ToolStripEx( );
        toolStripToolBar.BackColor = Color.White;
        toolStripToolBar.GripStyle = ToolStripGripStyle.Hidden;
        toolStripToolBar.Location = new Point(0, 0);
        toolStripToolBar.Name = "toolStripToolBar";
        toolStripToolBar.Renderer = new MenuItemRenderer( );
        toolStripToolBar.RenderMode = ToolStripRenderMode.System;
        toolStripToolBar.Size = new Size(600, 25);
        toolStripToolBar.TabIndex = 1;
        toolStripToolBar.Text = "Tool Bar";
        base.Text = "richTextBox";
        ((ToolStripDropDownMenu) ButtonFont.DropDown).ShowImageMargin = false;
        ((ToolStripDropDownMenu) ButtonLang.DropDown).ShowImageMargin = false;
        SuspendLayout( );
        toolStripToolBar.SuspendLayout( );
        Controls.Add(EditBox);
        Controls.Add(toolStripToolBar);
        toolStripToolBar.ResumeLayout(false);
        toolStripToolBar.PerformLayout( );
        ResumeLayout(false);
        PerformLayout( );
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null)
        {
            components.Dispose( );
        }
        base.Dispose(disposing);
    }
}
