using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;
using TrOCR.Properties;

namespace TrOCR
{
    public sealed partial class FmSetting : Form
    {
        private TextBox BoxBaiduId;
        private TextBox BoxBaiduKey;
        private CheckBox Box保存;
        private ComboBox Box代理;
        private CheckBox Box代理服务器;
        private TextBox Box代理密码;
        private TextBox Box代理账号;
        private CheckBox Box弹窗;
        private ComboBox Box动画;
        private TextBox Box端口;
        private CheckBox Box翻译;
        private TextBox Box翻译文本;
        private TextBox Box服务器;
        private CheckBox Box更新间隔;
        private TextBox Box更新说明;
        private NumericUpDown Box记录;
        private TextBox Box记录界面;
        private NumericUpDown Box间隔时间;
        private CheckBox Box检查更新;
        private CheckBox Box截图保存;
        private CheckBox Box截图剪贴板;
        private TextBox Box截图位置;
        private CheckBox Box开机;
        private CheckBox Box取色;
        private TextBox Box识别界面;
        private TextBox Box文字识别;
        private TextBox Box问题反馈;
        private TextBox Box音效路径;
        private Button btn_浏览;
        private Button btn_音效;
        private Button btn_音效路径;
        private Button Button反馈;
        private IContainer components;
        private GroupBox groupBox1;
        private GroupBox groupBox10;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private GroupBox groupBox4;
        private GroupBox groupBox5;
        private GroupBox groupBox6;
        private GroupBox groupBox7;
        private GroupBox groupBox8;
        private GroupBox groupBox9;
        private TabPage inPage百度接口;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label19;
        private Label label2;
        private Label label20;
        private Label label21;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private TabPage Page更新;
        private TabPage Page常规;
        private TabPage Page代理;
        private TabPage Page反馈;
        private TabPage Page关于;
        private TabPage Page快捷键;
        private TabPage Page密钥;
        private TabPage Page赞助;
        private PictureBox pic_help;
        private PictureBox pictureBox_翻译文本;
        private PictureBox pictureBox_记录界面;
        private PictureBox pictureBox_识别界面;
        private PictureBox pictureBox_文字识别;
        private PictureBox pictureBox6;
        private PictureBox pictureBox7;
        private TabControl tabControl;
        private TabControl tabControl2;
        private Label Text版本号;
        private Label Text更新日期;
        private Button 百度_btn;
        private Button 常规Button;
        private Button Button代理;
        private Button 更新Button;
        private Button 更新Button_check;
        private Button 快捷键Button;
        private Button 密钥Button;
        private Button 密钥Button_apply;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.Page代理 = new TabPage();
            this.Button代理 = new Button();
            this.groupBox4 = new GroupBox();
            this.Box代理服务器 = new CheckBox();
            this.Box代理密码 = new TextBox();
            this.Box端口 = new TextBox();
            this.label15 = new Label();
            this.Box代理账号 = new TextBox();
            this.Box服务器 = new TextBox();
            this.label14 = new Label();
            this.label13 = new Label();
            this.label12 = new Label();
            this.Box代理 = new ComboBox();
            this.label11 = new Label();
            this.Page密钥 = new TabPage();
            this.百度_btn = new Button();
            this.密钥Button_apply = new Button();
            this.密钥Button = new Button();
            this.tabControl2 = new TabControl();
            this.inPage百度接口 = new TabPage();
            this.BoxBaiduKey = new TextBox();
            this.BoxBaiduId = new TextBox();
            this.label10 = new Label();
            this.label9 = new Label();
            this.Page快捷键 = new TabPage();
            this.快捷键Button = new Button();
            this.label8 = new Label();
            this.groupBox3 = new GroupBox();
            this.pictureBox_识别界面 = new PictureBox();
            this.pictureBox_记录界面 = new PictureBox();
            this.pictureBox_翻译文本 = new PictureBox();
            this.pictureBox_文字识别 = new PictureBox();
            this.Box识别界面 = new TextBox();
            this.Box记录界面 = new TextBox();
            this.Box翻译文本 = new TextBox();
            this.Box文字识别 = new TextBox();
            this.label7 = new Label();
            this.label6 = new Label();
            this.label5 = new Label();
            this.label4 = new Label();
            this.Page常规 = new TabPage();
            this.groupBox10 = new GroupBox();
            this.Box截图保存 = new CheckBox();
            this.Box截图剪贴板 = new CheckBox();
            this.label20 = new Label();
            this.btn_音效路径 = new Button();
            this.btn_音效 = new Button();
            this.Box音效路径 = new TextBox();
            this.label18 = new Label();
            this.groupBox6 = new GroupBox();
            this.btn_浏览 = new Button();
            this.Box截图位置 = new TextBox();
            this.label1 = new Label();
            this.Box保存 = new CheckBox();
            this.pic_help = new PictureBox();
            this.常规Button = new Button();
            this.groupBox2 = new GroupBox();
            this.Box记录 = new NumericUpDown();
            this.label3 = new Label();
            this.Box动画 = new ComboBox();
            this.label2 = new Label();
            this.groupBox1 = new GroupBox();
            this.Box取色 = new CheckBox();
            this.Box弹窗 = new CheckBox();
            this.Box翻译 = new CheckBox();
            this.Box开机 = new CheckBox();
            this.tabControl = new TabControl();
            this.Page更新 = new TabPage();
            this.更新Button_check = new Button();
            this.更新Button = new Button();
            this.groupBox5 = new GroupBox();
            this.label16 = new Label();
            this.Box间隔时间 = new NumericUpDown();
            this.Box更新间隔 = new CheckBox();
            this.Box检查更新 = new CheckBox();
            this.Page关于 = new TabPage();
            this.groupBox9 = new GroupBox();
            this.Box更新说明 = new TextBox();
            this.groupBox7 = new GroupBox();
            this.pictureBox6 = new PictureBox();
            this.groupBox8 = new GroupBox();
            this.Text更新日期 = new Label();
            this.Text版本号 = new Label();
            this.label19 = new Label();
            this.label17 = new Label();
            this.Page赞助 = new TabPage();
            this.pictureBox7 = new PictureBox();
            this.Page反馈 = new TabPage();
            this.label21 = new Label();
            this.Button反馈 = new Button();
            this.Box问题反馈 = new TextBox();
            this.Page代理.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.Page密钥.SuspendLayout();
            this.tabControl2.SuspendLayout();
            this.inPage百度接口.SuspendLayout();
            this.Page快捷键.SuspendLayout();
            this.groupBox3.SuspendLayout();
            ((ISupportInitialize)this.pictureBox_识别界面).BeginInit();
            ((ISupportInitialize)this.pictureBox_记录界面).BeginInit();
            ((ISupportInitialize)this.pictureBox_翻译文本).BeginInit();
            ((ISupportInitialize)this.pictureBox_文字识别).BeginInit();
            this.Page常规.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox6.SuspendLayout();
            ((ISupportInitialize)this.pic_help).BeginInit();
            this.groupBox2.SuspendLayout();
            ((ISupportInitialize)this.Box记录).BeginInit();
            this.groupBox1.SuspendLayout();
            this.tabControl.SuspendLayout();
            this.Page更新.SuspendLayout();
            this.groupBox5.SuspendLayout();
            ((ISupportInitialize)this.Box间隔时间).BeginInit();
            this.Page关于.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox7.SuspendLayout();
            ((ISupportInitialize)this.pictureBox6).BeginInit();
            this.groupBox8.SuspendLayout();
            this.Page赞助.SuspendLayout();
            ((ISupportInitialize)this.pictureBox7).BeginInit();
            this.Page反馈.SuspendLayout();
            base.SuspendLayout();
            this.Page代理.BackColor = Color.White;
            this.Page代理.Controls.Add(this.Button代理);
            this.Page代理.Controls.Add(this.groupBox4);
            this.Page代理.Location = new Point(4, 22);
            this.Page代理.Name = "Page_代理";
            this.Page代理.Padding = new Padding(3);
            this.Page代理.Size = new Size(390, 329);
            this.Page代理.TabIndex = 4;
            this.Page代理.Text = "代理";
            this.Button代理.BackColor = Color.White;
            this.Button代理.Location = new Point(309, 193);
            this.Button代理.Name = "代理Button";
            this.Button代理.Size = new Size(75, 23);
            this.Button代理.TabIndex = 9;
            this.Button代理.Text = "恢复默认";
            this.Button代理.UseVisualStyleBackColor = false;
            this.Button代理.Click += new global::System.EventHandler(this.代理Click);
            this.groupBox4.Controls.Add(this.Box代理服务器);
            this.groupBox4.Controls.Add(this.Box代理密码);
            this.groupBox4.Controls.Add(this.Box端口);
            this.groupBox4.Controls.Add(this.label15);
            this.groupBox4.Controls.Add(this.Box代理账号);
            this.groupBox4.Controls.Add(this.Box服务器);
            this.groupBox4.Controls.Add(this.label14);
            this.groupBox4.Controls.Add(this.label13);
            this.groupBox4.Controls.Add(this.label12);
            this.groupBox4.Controls.Add(this.Box代理);
            this.groupBox4.Controls.Add(this.label11);
            this.groupBox4.Location = new Point(3, 6);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(381, 183);
            this.groupBox4.TabIndex = 0;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "代理";
            this.Box代理服务器.AutoSize = true;
            this.Box代理服务器.Location = new Point(78, 84);
            this.Box代理服务器.Name = "chbox_代理服务器";
            this.Box代理服务器.Size = new Size(132, 16);
            this.Box代理服务器.TabIndex = 12;
            this.Box代理服务器.Text = "代理服务器需要密码";
            this.Box代理服务器.UseVisualStyleBackColor = true;
            this.Box代理密码.Location = new Point(78, 144);
            this.Box代理密码.Name = "text_密码";
            this.Box代理密码.Size = new Size(128, 21);
            this.Box代理密码.TabIndex = 11;
            this.Box端口.Location = new Point(248, 52);
            this.Box端口.Name = "text_端口";
            this.Box端口.Size = new Size(55, 21);
            this.Box端口.TabIndex = 10;
            this.Box端口.Text = " ";
            this.label15.AutoSize = true;
            this.label15.Location = new Point(212, 57);
            this.label15.Name = "label15";
            this.label15.Size = new Size(41, 12);
            this.label15.TabIndex = 9;
            this.label15.Text = "端口：";
            this.Box代理账号.Location = new Point(78, 110);
            this.Box代理账号.Name = "text_账号";
            this.Box代理账号.Size = new Size(128, 21);
            this.Box代理账号.TabIndex = 8;
            this.Box服务器.Location = new Point(78, 52);
            this.Box服务器.Name = "text_服务器";
            this.Box服务器.Size = new Size(128, 21);
            this.Box服务器.TabIndex = 7;
            this.label14.AutoSize = true;
            this.label14.Location = new Point(9, 147);
            this.label14.Name = "label14";
            this.label14.Size = new Size(41, 12);
            this.label14.TabIndex = 6;
            this.label14.Text = "密码：";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(9, 114);
            this.label13.Name = "label13";
            this.label13.Size = new Size(53, 12);
            this.label13.TabIndex = 5;
            this.label13.Text = "用户名：";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(9, 57);
            this.label12.Name = "label12";
            this.label12.Size = new Size(53, 12);
            this.label12.TabIndex = 4;
            this.label12.Text = "服务器：";
            this.Box代理.BackColor = Color.White;
            this.Box代理.DropDownStyle = ComboBoxStyle.DropDownList;
            this.Box代理.FormattingEnabled = true;
            this.Box代理.Items.AddRange(new object[] { "不使用代理", "系统代理", "自定义代理" });
            this.Box代理.Location = new Point(78, 18);
            this.Box代理.Name = "combox_代理";
            this.Box代理.Size = new Size(95, 20);
            this.Box代理.TabIndex = 3;
            this.Box代理.SelectedIndexChanged += new global::System.EventHandler(this.combox_代理_SelectedIndexChanged);
            this.label11.AutoSize = true;
            this.label11.Location = new Point(7, 22);
            this.label11.Name = "label11";
            this.label11.Size = new Size(65, 12);
            this.label11.TabIndex = 0;
            this.label11.Text = "代理类型：";
            this.Page密钥.BackColor = Color.White;
            this.Page密钥.Controls.Add(this.百度_btn);
            this.Page密钥.Controls.Add(this.密钥Button_apply);
            this.Page密钥.Controls.Add(this.密钥Button);
            this.Page密钥.Controls.Add(this.tabControl2);
            this.Page密钥.Location = new Point(4, 22);
            this.Page密钥.Name = "Page_密钥";
            this.Page密钥.Padding = new Padding(3);
            this.Page密钥.Size = new Size(390, 329);
            this.Page密钥.TabIndex = 3;
            this.Page密钥.Text = "密钥";
            this.百度_btn.BackColor = Color.White;
            this.百度_btn.Location = new Point(152, 136);
            this.百度_btn.Name = "百度_btn";
            this.百度_btn.Size = new Size(75, 23);
            this.百度_btn.TabIndex = 10;
            this.百度_btn.Text = "密钥测试";
            this.百度_btn.UseVisualStyleBackColor = false;
            this.百度_btn.Click += new global::System.EventHandler(this.百度_btn_Click);
            this.密钥Button_apply.BackColor = Color.White;
            this.密钥Button_apply.Location = new Point(6, 136);
            this.密钥Button_apply.Name = "密钥Button_apply";
            this.密钥Button_apply.Size = new Size(75, 23);
            this.密钥Button_apply.TabIndex = 9;
            this.密钥Button_apply.Text = "接口申请";
            this.密钥Button_apply.UseVisualStyleBackColor = false;
            this.密钥Button_apply.Click += new global::System.EventHandler(this.百度申请Click);
            this.密钥Button.BackColor = Color.White;
            this.密钥Button.Location = new Point(309, 136);
            this.密钥Button.Name = "密钥Button";
            this.密钥Button.Size = new Size(75, 23);
            this.密钥Button.TabIndex = 8;
            this.密钥Button.Text = "恢复默认";
            this.密钥Button.UseVisualStyleBackColor = false;
            this.密钥Button.Click += new global::System.EventHandler(this.密钥Click);
            this.tabControl2.Controls.Add(this.inPage百度接口);
            this.tabControl2.Location = new Point(6, 6);
            this.tabControl2.Name = "tabControl2";
            this.tabControl2.SelectedIndex = 0;
            this.tabControl2.Size = new Size(378, 124);
            this.tabControl2.TabIndex = 0;
            this.inPage百度接口.BackColor = Color.White;
            this.inPage百度接口.Controls.Add(this.BoxBaiduKey);
            this.inPage百度接口.Controls.Add(this.BoxBaiduId);
            this.inPage百度接口.Controls.Add(this.label10);
            this.inPage百度接口.Controls.Add(this.label9);
            this.inPage百度接口.Location = new Point(4, 22);
            this.inPage百度接口.Name = "inPage_百度接口";
            this.inPage百度接口.Padding = new Padding(3);
            this.inPage百度接口.Size = new Size(370, 98);
            this.inPage百度接口.TabIndex = 0;
            this.inPage百度接口.Text = "百度识别接口";
            this.BoxBaiduKey.BackColor = Color.White;
            this.BoxBaiduKey.Location = new Point(56, 55);
            this.BoxBaiduKey.Name = "text_baidupassword";
            this.BoxBaiduKey.Size = new Size(260, 21);
            this.BoxBaiduKey.TabIndex = 3;
            this.BoxBaiduId.BackColor = Color.White;
            this.BoxBaiduId.Location = new Point(56, 20);
            this.BoxBaiduId.Name = "text_baiduaccount";
            this.BoxBaiduId.Size = new Size(260, 21);
            this.BoxBaiduId.TabIndex = 2;
            this.label10.AutoSize = true;
            this.label10.Location = new Point(18, 58);
            this.label10.Name = "label10";
            this.label10.Size = new Size(41, 12);
            this.label10.TabIndex = 1;
            this.label10.Text = "密码：";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(18, 23);
            this.label9.Name = "label9";
            this.label9.Size = new Size(41, 12);
            this.label9.TabIndex = 0;
            this.label9.Text = "账号：";
            this.Page快捷键.BackColor = Color.White;
            this.Page快捷键.Controls.Add(this.快捷键Button);
            this.Page快捷键.Controls.Add(this.label8);
            this.Page快捷键.Controls.Add(this.groupBox3);
            this.Page快捷键.Location = new Point(4, 22);
            this.Page快捷键.Name = "Page_快捷键";
            this.Page快捷键.Padding = new Padding(3);
            this.Page快捷键.Size = new Size(390, 329);
            this.Page快捷键.TabIndex = 2;
            this.Page快捷键.Text = "快捷键";
            this.快捷键Button.BackColor = Color.White;
            this.快捷键Button.Location = new Point(309, 175);
            this.快捷键Button.Name = "快捷键Button";
            this.快捷键Button.Size = new Size(75, 23);
            this.快捷键Button.TabIndex = 7;
            this.快捷键Button.Text = "恢复默认";
            this.快捷键Button.UseVisualStyleBackColor = false;
            this.快捷键Button.Click += new global::System.EventHandler(this.快捷键Click);
            this.label8.AutoSize = true;
            this.label8.Location = new Point(6, 180);
            this.label8.Name = "label8";
            this.label8.Size = new Size(209, 12);
            this.label8.TabIndex = 1;
            this.label8.Text = "说明：按Backspace键可清除当前快捷键";
            this.groupBox3.Controls.Add(this.pictureBox_识别界面);
            this.groupBox3.Controls.Add(this.pictureBox_记录界面);
            this.groupBox3.Controls.Add(this.pictureBox_翻译文本);
            this.groupBox3.Controls.Add(this.pictureBox_文字识别);
            this.groupBox3.Controls.Add(this.Box识别界面);
            this.groupBox3.Controls.Add(this.Box记录界面);
            this.groupBox3.Controls.Add(this.Box翻译文本);
            this.groupBox3.Controls.Add(this.Box文字识别);
            this.groupBox3.Controls.Add(this.label7);
            this.groupBox3.Controls.Add(this.label6);
            this.groupBox3.Controls.Add(this.label5);
            this.groupBox3.Controls.Add(this.label4);
            this.groupBox3.Location = new Point(6, 6);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(378, 163);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "全局快捷键";
            this.pictureBox_识别界面.Image = Resources.快捷键_1;
            this.pictureBox_识别界面.Location = new Point(351, 122);
            this.pictureBox_识别界面.Name = "pictureBox_识别界面";
            this.pictureBox_识别界面.Size = new Size(21, 21);
            this.pictureBox_识别界面.SizeMode = PictureBoxSizeMode.CenterImage;
            this.pictureBox_识别界面.TabIndex = 11;
            this.pictureBox_识别界面.TabStop = false;
            this.pictureBox_记录界面.Image = Resources.快捷键_1;
            this.pictureBox_记录界面.Location = new Point(351, 89);
            this.pictureBox_记录界面.Name = "pictureBox_记录界面";
            this.pictureBox_记录界面.Size = new Size(21, 21);
            this.pictureBox_记录界面.SizeMode = PictureBoxSizeMode.CenterImage;
            this.pictureBox_记录界面.TabIndex = 10;
            this.pictureBox_记录界面.TabStop = false;
            this.pictureBox_翻译文本.Image = Resources.快捷键_1;
            this.pictureBox_翻译文本.Location = new Point(351, 52);
            this.pictureBox_翻译文本.Name = "pictureBox_翻译文本";
            this.pictureBox_翻译文本.Size = new Size(21, 21);
            this.pictureBox_翻译文本.SizeMode = PictureBoxSizeMode.CenterImage;
            this.pictureBox_翻译文本.TabIndex = 9;
            this.pictureBox_翻译文本.TabStop = false;
            this.pictureBox_文字识别.Image = Resources.快捷键_1;
            this.pictureBox_文字识别.Location = new Point(351, 19);
            this.pictureBox_文字识别.Name = "pictureBox_文字识别";
            this.pictureBox_文字识别.Size = new Size(21, 21);
            this.pictureBox_文字识别.SizeMode = PictureBoxSizeMode.CenterImage;
            this.pictureBox_文字识别.TabIndex = 8;
            this.pictureBox_文字识别.TabStop = false;
            this.Box识别界面.Font = new Font("微软雅黑", 9f);
            this.Box识别界面.Location = new Point(78, 122);
            this.Box识别界面.Name = "txtBox_识别界面";
            this.Box识别界面.Size = new Size(260, 23);
            this.Box识别界面.TabIndex = 7;
            this.Box识别界面.TextAlign = HorizontalAlignment.Center;
            this.Box识别界面.KeyDown += new KeyEventHandler(this.TextBoxKeyDown);
            this.Box识别界面.KeyUp += new KeyEventHandler(this.TextBoxKeyUp);
            this.Box记录界面.Font = new Font("微软雅黑", 9f);
            this.Box记录界面.Location = new Point(78, 89);
            this.Box记录界面.Name = "txtBox_记录界面";
            this.Box记录界面.Size = new Size(260, 23);
            this.Box记录界面.TabIndex = 6;
            this.Box记录界面.TextAlign = HorizontalAlignment.Center;
            this.Box记录界面.KeyDown += new KeyEventHandler(this.TextBoxKeyDown);
            this.Box记录界面.KeyUp += new KeyEventHandler(this.TextBoxKeyUp);
            this.Box翻译文本.Font = new Font("微软雅黑", 9f);
            this.Box翻译文本.Location = new Point(78, 52);
            this.Box翻译文本.Name = "txtBox_翻译文本";
            this.Box翻译文本.Size = new Size(260, 23);
            this.Box翻译文本.TabIndex = 5;
            this.Box翻译文本.TextAlign = HorizontalAlignment.Center;
            this.Box翻译文本.KeyDown += new KeyEventHandler(this.TextBoxKeyDown);
            this.Box翻译文本.KeyUp += new KeyEventHandler(this.TextBoxKeyUp);
            this.Box文字识别.Font = new Font("微软雅黑", 9f);
            this.Box文字识别.Location = new Point(78, 19);
            this.Box文字识别.Name = "txtBox_文字识别";
            this.Box文字识别.Size = new Size(260, 23);
            this.Box文字识别.TabIndex = 4;
            this.Box文字识别.TabStop = false;
            this.Box文字识别.TextAlign = HorizontalAlignment.Center;
            this.Box文字识别.KeyDown += new KeyEventHandler(this.TextBoxKeyDown);
            this.Box文字识别.KeyUp += new KeyEventHandler(this.TextBoxKeyUp);
            this.label7.AutoSize = true;
            this.label7.Location = new Point(6, 125);
            this.label7.Name = "label7";
            this.label7.Size = new Size(65, 12);
            this.label7.TabIndex = 3;
            this.label7.Text = "识别界面：";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(7, 92);
            this.label6.Name = "label6";
            this.label6.Size = new Size(65, 12);
            this.label6.TabIndex = 2;
            this.label6.Text = "记录界面：";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(6, 58);
            this.label5.Name = "label5";
            this.label5.Size = new Size(65, 12);
            this.label5.TabIndex = 1;
            this.label5.Text = "翻译文本：";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(7, 24);
            this.label4.Name = "label4";
            this.label4.Size = new Size(65, 12);
            this.label4.TabIndex = 0;
            this.label4.Text = "文字识别：";
            this.Page常规.BackColor = Color.White;
            this.Page常规.Controls.Add(this.groupBox10);
            this.Page常规.Controls.Add(this.groupBox6);
            this.Page常规.Controls.Add(this.pic_help);
            this.Page常规.Controls.Add(this.常规Button);
            this.Page常规.Controls.Add(this.groupBox2);
            this.Page常规.Controls.Add(this.groupBox1);
            this.Page常规.Location = new Point(4, 22);
            this.Page常规.Name = "page_常规";
            this.Page常规.Padding = new Padding(3);
            this.Page常规.Size = new Size(390, 329);
            this.Page常规.TabIndex = 0;
            this.Page常规.Text = "常规";
            this.groupBox10.Controls.Add(this.Box截图保存);
            this.groupBox10.Controls.Add(this.Box截图剪贴板);
            this.groupBox10.Controls.Add(this.label20);
            this.groupBox10.Controls.Add(this.btn_音效路径);
            this.groupBox10.Controls.Add(this.btn_音效);
            this.groupBox10.Controls.Add(this.Box音效路径);
            this.groupBox10.Controls.Add(this.label18);
            this.groupBox10.Location = new Point(6, 136);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new Size(378, 86);
            this.groupBox10.TabIndex = 8;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "音效";
            this.Box截图保存.AutoSize = true;
            this.Box截图保存.Checked = true;
            this.Box截图保存.CheckState = CheckState.Checked;
            this.Box截图保存.Location = new Point(167, 54);
            this.Box截图保存.Name = "chbox_save";
            this.Box截图保存.Size = new Size(96, 16);
            this.Box截图保存.TabIndex = 10;
            this.Box截图保存.Text = "快速保存图片";
            this.Box截图保存.UseVisualStyleBackColor = true;
            this.Box截图保存.CheckedChanged += new global::System.EventHandler(this.chbox_save_CheckedChanged);
            this.Box截图剪贴板.AutoSize = true;
            this.Box截图剪贴板.Location = new Point(53, 54);
            this.Box截图剪贴板.Name = "chbox_copy";
            this.Box截图剪贴板.Size = new Size(96, 16);
            this.Box截图剪贴板.TabIndex = 6;
            this.Box截图剪贴板.Text = "复制到剪贴板";
            this.Box截图剪贴板.UseVisualStyleBackColor = true;
            this.Box截图剪贴板.CheckedChanged += new global::System.EventHandler(this.chbox_copy_CheckedChanged);
            this.label20.AutoSize = true;
            this.label20.Location = new Point(14, 55);
            this.label20.Name = "label20";
            this.label20.Size = new Size(41, 12);
            this.label20.TabIndex = 9;
            this.label20.Text = "何时：";
            this.btn_音效路径.BackColor = Color.White;
            this.btn_音效路径.Location = new Point(332, 49);
            this.btn_音效路径.Name = "btn_音效路径";
            this.btn_音效路径.Size = new Size(40, 23);
            this.btn_音效路径.TabIndex = 8;
            this.btn_音效路径.Text = "更改";
            this.btn_音效路径.UseVisualStyleBackColor = false;
            this.btn_音效路径.Click += new global::System.EventHandler(this.btn_音效路径_Click);
            this.btn_音效.BackColor = Color.White;
            this.btn_音效.Image = Resources.语音按钮;
            this.btn_音效.Location = new Point(344, 17);
            this.btn_音效.Name = "btn_音效";
            this.btn_音效.Size = new Size(26, 23);
            this.btn_音效.TabIndex = 7;
            this.btn_音效.UseVisualStyleBackColor = false;
            this.btn_音效.Click += new global::System.EventHandler(this.btn_音效_Click);
            this.Box音效路径.BackColor = Color.White;
            this.Box音效路径.Location = new Point(51, 19);
            this.Box音效路径.Name = "text_音效path";
            this.Box音效路径.ReadOnly = true;
            this.Box音效路径.Size = new Size(288, 21);
            this.Box音效路径.TabIndex = 4;
            this.Box音效路径.Text = "Data\\screenshot.wav";
            this.label18.AutoSize = true;
            this.label18.Location = new Point(13, 22);
            this.label18.Name = "label18";
            this.label18.Size = new Size(41, 12);
            this.label18.TabIndex = 3;
            this.label18.Text = "文件：";
            this.groupBox6.Controls.Add(this.btn_浏览);
            this.groupBox6.Controls.Add(this.Box截图位置);
            this.groupBox6.Controls.Add(this.label1);
            this.groupBox6.Controls.Add(this.Box保存);
            this.groupBox6.Location = new Point(6, 227);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(378, 63);
            this.groupBox6.TabIndex = 6;
            this.groupBox6.TabStop = false;
            this.btn_浏览.BackColor = Color.White;
            this.btn_浏览.Location = new Point(332, 24);
            this.btn_浏览.Name = "btn_浏览";
            this.btn_浏览.Size = new Size(40, 23);
            this.btn_浏览.TabIndex = 7;
            this.btn_浏览.Text = "浏览";
            this.btn_浏览.UseVisualStyleBackColor = false;
            this.btn_浏览.Click += new global::System.EventHandler(this.btn_浏览_Click);
            this.Box截图位置.BackColor = Color.White;
            this.Box截图位置.Location = new Point(51, 26);
            this.Box截图位置.Name = "textBox_path";
            this.Box截图位置.ReadOnly = true;
            this.Box截图位置.Size = new Size(275, 21);
            this.Box截图位置.TabIndex = 4;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(15, 29);
            this.label1.Name = "label1";
            this.label1.Size = new Size(41, 12);
            this.label1.TabIndex = 3;
            this.label1.Text = "目录：";
            this.Box保存.AutoSize = true;
            this.Box保存.BackColor = Color.White;
            this.Box保存.Location = new Point(6, 0);
            this.Box保存.Name = "cbBox_保存";
            this.Box保存.Size = new Size(72, 16);
            this.Box保存.TabIndex = 2;
            this.Box保存.Text = "自动保存";
            this.Box保存.UseVisualStyleBackColor = false;
            this.Box保存.CheckedChanged += new global::System.EventHandler(this.cbBox_保存_CheckedChanged);
            this.pic_help.Image = Resources.帮助;
            this.pic_help.Location = new Point(7, 296);
            this.pic_help.Name = "pic_help";
            this.pic_help.Size = new Size(27, 23);
            this.pic_help.TabIndex = 7;
            this.pic_help.TabStop = false;
            this.pic_help.Click += new global::System.EventHandler(this.PictureHelpClick);
            this.常规Button.BackColor = Color.White;
            this.常规Button.Location = new Point(310, 297);
            this.常规Button.Name = "常规Button";
            this.常规Button.Size = new Size(75, 23);
            this.常规Button.TabIndex = 6;
            this.常规Button.Text = "恢复默认";
            this.常规Button.UseVisualStyleBackColor = false;
            this.常规Button.Click += new global::System.EventHandler(this.常规Click);
            this.groupBox2.Controls.Add(this.Box记录);
            this.groupBox2.Controls.Add(this.label3);
            this.groupBox2.Controls.Add(this.Box动画);
            this.groupBox2.Controls.Add(this.label2);
            this.groupBox2.Location = new Point(6, 60);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(378, 70);
            this.groupBox2.TabIndex = 4;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "界面";
            this.Box记录.Location = new Point(276, 28);
            this.Box记录.Name = "numbox_记录";
            this.Box记录.Size = new Size(63, 21);
            this.Box记录.TabIndex = 5;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(205, 32);
            this.label3.Name = "label3";
            this.label3.Size = new Size(65, 12);
            this.label3.TabIndex = 4;
            this.label3.Text = "记录数目：";
            this.Box动画.BackColor = Color.White;
            this.Box动画.DropDownStyle = ComboBoxStyle.DropDownList;
            this.Box动画.FormattingEnabled = true;
            this.Box动画.Items.AddRange(new object[] { "窗体", "少女", "罗小黑" });
            this.Box动画.Location = new Point(84, 30);
            this.Box动画.Name = "cobBox_动画";
            this.Box动画.Size = new Size(63, 20);
            this.Box动画.TabIndex = 3;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(13, 33);
            this.label2.Name = "label2";
            this.label2.Size = new Size(65, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "窗体动画：";
            this.groupBox1.Controls.Add(this.Box取色);
            this.groupBox1.Controls.Add(this.Box弹窗);
            this.groupBox1.Controls.Add(this.Box翻译);
            this.groupBox1.Controls.Add(this.Box开机);
            this.groupBox1.Location = new Point(6, 6);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(378, 48);
            this.groupBox1.TabIndex = 2;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "设置";
            this.Box取色.AutoSize = true;
            this.Box取色.Location = new Point(298, 20);
            this.Box取色.Name = "chbox_取色";
            this.Box取色.Size = new Size(66, 16);
            this.Box取色.TabIndex = 6;
            this.Box取色.Text = "取色HEX";
            this.Box取色.UseVisualStyleBackColor = true;
            this.Box取色.CheckedChanged += new global::System.EventHandler(this.chbox_取色_CheckedChanged);
            this.Box弹窗.AutoSize = true;
            this.Box弹窗.Location = new Point(204, 20);
            this.Box弹窗.Name = "cbBox_弹窗";
            this.Box弹窗.Size = new Size(72, 16);
            this.Box弹窗.TabIndex = 5;
            this.Box弹窗.Text = "识别弹窗";
            this.Box弹窗.UseVisualStyleBackColor = true;
            this.Box弹窗.CheckedChanged += new global::System.EventHandler(this.cbBox_弹窗_CheckedChanged);
            this.Box翻译.AutoSize = true;
            this.Box翻译.Location = new Point(107, 20);
            this.Box翻译.Name = "cbBox_翻译";
            this.Box翻译.Size = new Size(72, 16);
            this.Box翻译.TabIndex = 4;
            this.Box翻译.Text = "快速翻译";
            this.Box翻译.UseVisualStyleBackColor = true;
            this.Box翻译.CheckedChanged += new global::System.EventHandler(this.cbBox_翻译_CheckedChanged);
            this.Box开机.AutoSize = true;
            this.Box开机.Location = new Point(17, 20);
            this.Box开机.Name = "cbBox_开机";
            this.Box开机.Size = new Size(72, 16);
            this.Box开机.TabIndex = 2;
            this.Box开机.Text = "开机启动";
            this.Box开机.UseVisualStyleBackColor = true;
            this.Box开机.CheckedChanged += new global::System.EventHandler(this.cbBox_开机_CheckedChanged);
            this.tabControl.Controls.Add(this.Page常规);
            this.tabControl.Controls.Add(this.Page快捷键);
            this.tabControl.Controls.Add(this.Page密钥);
            this.tabControl.Controls.Add(this.Page代理);
            this.tabControl.Controls.Add(this.Page更新);
            this.tabControl.Controls.Add(this.Page关于);
            this.tabControl.Controls.Add(this.Page赞助);
            this.tabControl.Controls.Add(this.Page反馈);
            this.tabControl.Location = new Point(10, 2);
            this.tabControl.Name = "tab_标签";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new Size(398, 355);
            this.tabControl.TabIndex = 0;
            this.tabControl.SelectedIndexChanged += new global::System.EventHandler(this.TabControlSelectionChanged);
            this.Page更新.Controls.Add(this.更新Button_check);
            this.Page更新.Controls.Add(this.更新Button);
            this.Page更新.Controls.Add(this.groupBox5);
            this.Page更新.Location = new Point(4, 22);
            this.Page更新.Name = "Page_更新";
            this.Page更新.Padding = new Padding(3);
            this.Page更新.Size = new Size(390, 329);
            this.Page更新.TabIndex = 5;
            this.Page更新.Text = "更新";
            this.Page更新.BackColor = Color.White;
            this.Page更新.UseVisualStyleBackColor = true;
            this.更新Button_check.BackColor = Color.White;
            this.更新Button_check.Location = new Point(6, 83);
            this.更新Button_check.Name = "更新Button_check";
            this.更新Button_check.Size = new Size(75, 23);
            this.更新Button_check.TabIndex = 11;
            this.更新Button_check.Text = "检查更新";
            this.更新Button_check.UseVisualStyleBackColor = false;
            this.更新Button.BackColor = Color.White;
            this.更新Button.Location = new Point(309, 83);
            this.更新Button.Name = "更新Button";
            this.更新Button.Size = new Size(75, 23);
            this.更新Button.TabIndex = 10;
            this.更新Button.Text = "恢复默认";
            this.更新Button.UseVisualStyleBackColor = false;
            this.更新Button.Click += new global::System.EventHandler(this.更新Click);
            this.groupBox5.Controls.Add(this.label16);
            this.groupBox5.Controls.Add(this.Box间隔时间);
            this.groupBox5.Controls.Add(this.Box更新间隔);
            this.groupBox5.Controls.Add(this.Box检查更新);
            this.groupBox5.Location = new Point(6, 14);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(378, 65);
            this.groupBox5.TabIndex = 0;
            this.groupBox5.TabStop = false;
            this.label16.AutoSize = true;
            this.label16.Location = new Point(98, 31);
            this.label16.Name = "label16";
            this.label16.Size = new Size(29, 12);
            this.label16.TabIndex = 3;
            this.label16.Text = "小时";
            this.Box间隔时间.Location = new Point(54, 27);
            this.Box间隔时间.Name = "numbox_间隔时间";
            this.Box间隔时间.Size = new Size(37, 21);
            this.Box间隔时间.TabIndex = 2;
            this.Box更新间隔.AutoSize = true;
            this.Box更新间隔.Location = new Point(6, 31);
            this.Box更新间隔.Name = "checkBox_更新间隔";
            this.Box更新间隔.Size = new Size(48, 16);
            this.Box更新间隔.TabIndex = 1;
            this.Box更新间隔.Text = "每隔";
            this.Box更新间隔.UseVisualStyleBackColor = true;
            this.Box更新间隔.CheckedChanged += new global::System.EventHandler(this.checkBox_更新间隔_CheckedChanged);
            this.Box检查更新.AutoSize = true;
            this.Box检查更新.BackColor = Color.White;
            this.Box检查更新.Location = new Point(6, 0);
            this.Box检查更新.Name = "check_检查更新";
            this.Box检查更新.Size = new Size(108, 16);
            this.Box检查更新.TabIndex = 0;
            this.Box检查更新.Text = "启动时检查更新";
            this.Box检查更新.UseVisualStyleBackColor = false;
            this.Box检查更新.CheckedChanged += new global::System.EventHandler(this.check_检查更新_CheckedChanged);
            this.Page关于.BackColor = Color.White;
            this.Page关于.Controls.Add(this.groupBox9);
            this.Page关于.Controls.Add(this.groupBox7);
            this.Page关于.Controls.Add(this.label17);
            this.Page关于.Location = new Point(4, 22);
            this.Page关于.Name = "Page_关于";
            this.Page关于.Padding = new Padding(3);
            this.Page关于.Size = new Size(390, 329);
            this.Page关于.TabIndex = 6;
            this.Page关于.Text = "关于";
            this.groupBox9.Controls.Add(this.Box更新说明);
            this.groupBox9.Location = new Point(6, 122);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new Size(378, 186);
            this.groupBox9.TabIndex = 5;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "更新说明";
            this.Box更新说明.BackColor = Color.White;
            this.Box更新说明.BorderStyle = BorderStyle.FixedSingle;
            this.Box更新说明.Location = new Point(6, 20);
            this.Box更新说明.Multiline = true;
            this.Box更新说明.Name = "txt_更新说明";
            this.Box更新说明.Size = new Size(366, 155);
            this.Box更新说明.TabIndex = 4;
            this.groupBox7.Controls.Add(this.pictureBox6);
            this.groupBox7.Controls.Add(this.groupBox8);
            this.groupBox7.Location = new Point(6, 8);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new Size(378, 108);
            this.groupBox7.TabIndex = 3;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "软件信息";
            this.pictureBox6.BackColor = Color.White;
            this.pictureBox6.Image = Resources.头像;
            this.pictureBox6.Location = new Point(12, 15);
            this.pictureBox6.Name = "pictureBox6";
            this.pictureBox6.Size = new Size(84, 82);
            this.pictureBox6.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBox6.TabIndex = 5;
            this.pictureBox6.TabStop = false;
            this.groupBox8.Controls.Add(this.Text更新日期);
            this.groupBox8.Controls.Add(this.Text版本号);
            this.groupBox8.Controls.Add(this.label19);
            this.groupBox8.Location = new Point(117, 14);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new Size(255, 83);
            this.groupBox8.TabIndex = 4;
            this.groupBox8.TabStop = false;
            this.Text更新日期.AutoSize = true;
            this.Text更新日期.Location = new Point(13, 34);
            this.Text更新日期.Name = "label_更新日期";
            this.Text更新日期.Size = new Size(125, 12);
            this.Text更新日期.TabIndex = 6;
            this.Text更新日期.Text = "更新时间：2018-06-29";
            this.Text版本号.AutoSize = true;
            this.Text版本号.Location = new Point(13, 13);
            this.Text版本号.Name = "label_版本号";
            this.Text版本号.Size = new Size(89, 12);
            this.Text版本号.TabIndex = 4;
            this.Text版本号.Text = "当前版本：4.34";
            this.label19.AutoSize = true;
            this.label19.Location = new Point(13, 56);
            this.label19.Name = "label19";
            this.label19.Size = new Size(113, 12);
            this.label19.TabIndex = 5;
            this.label19.Text = "版权所有：天若幽心";
            this.label17.AutoSize = true;
            this.label17.Font = new Font("微软雅黑", 12f);
            this.label17.Location = new Point(7, 8);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0, 21);
            this.label17.TabIndex = 0;
            this.Page赞助.BackColor = Color.White;
            this.Page赞助.Controls.Add(this.pictureBox7);
            this.Page赞助.Location = new Point(4, 22);
            this.Page赞助.Name = "Page_赞助";
            this.Page赞助.Padding = new Padding(3);
            this.Page赞助.Size = new Size(390, 329);
            this.Page赞助.TabIndex = 7;
            this.Page赞助.Text = "赞助";
            this.pictureBox7.Image = Resources.二维码;
            this.pictureBox7.Location = new Point(-3, -4);
            this.pictureBox7.Name = "pictureBox7";
            this.pictureBox7.Size = new Size(392, 208);
            this.pictureBox7.SizeMode = PictureBoxSizeMode.Zoom;
            this.pictureBox7.TabIndex = 0;
            this.pictureBox7.TabStop = false;
            this.Page反馈.BackColor = Color.White;
            this.Page反馈.Controls.Add(this.label21);
            this.Page反馈.Controls.Add(this.Button反馈);
            this.Page反馈.Controls.Add(this.Box问题反馈);
            this.Page反馈.Location = new Point(4, 22);
            this.Page反馈.Name = "Page_反馈";
            this.Page反馈.Padding = new Padding(3);
            this.Page反馈.Size = new Size(390, 329);
            this.Page反馈.TabIndex = 8;
            this.Page反馈.Text = "反馈";
            this.label21.AutoSize = true;
            this.label21.Location = new Point(7, 151);
            this.label21.Name = "label21";
            this.label21.Size = new Size(293, 12);
            this.label21.TabIndex = 12;
            this.label21.Text = "如果想要更好的获得更新信息，请备注您的联系方式！";
            this.Button反馈.BackColor = Color.White;
            this.Button反馈.Location = new Point(309, 146);
            this.Button反馈.Name = "反馈Button";
            this.Button反馈.Size = new Size(75, 23);
            this.Button反馈.TabIndex = 11;
            this.Button反馈.Text = "提交";
            this.Button反馈.UseVisualStyleBackColor = false;
            this.Button反馈.Click += new global::System.EventHandler(this.反馈Click);
            this.Box问题反馈.BackColor = Color.White;
            this.Box问题反馈.BorderStyle = BorderStyle.FixedSingle;
            this.Box问题反馈.ImeMode = ImeMode.HangulFull;
            this.Box问题反馈.Location = new Point(6, 6);
            this.Box问题反馈.Multiline = true;
            this.Box问题反馈.Name = "txt_问题反馈";
            this.Box问题反馈.Size = new Size(378, 134);
            this.Box问题反馈.TabIndex = 5;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.White;
            base.ClientSize = new Size(417, 368);
            base.Controls.Add(this.tabControl);
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.MinimizeBox = false;
            base.Name = "FmSetting";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "设置";
            base.FormClosed += new FormClosedEventHandler(this.FormClosed);
            base.Load += new global::System.EventHandler(this.FormLoaded);
            this.Page代理.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.Page密钥.ResumeLayout(false);
            this.tabControl2.ResumeLayout(false);
            this.inPage百度接口.ResumeLayout(false);
            this.inPage百度接口.PerformLayout();
            this.Page快捷键.ResumeLayout(false);
            this.Page快捷键.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((ISupportInitialize)this.pictureBox_识别界面).EndInit();
            ((ISupportInitialize)this.pictureBox_记录界面).EndInit();
            ((ISupportInitialize)this.pictureBox_翻译文本).EndInit();
            ((ISupportInitialize)this.pictureBox_文字识别).EndInit();
            this.Page常规.ResumeLayout(false);
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            ((ISupportInitialize)this.pic_help).EndInit();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((ISupportInitialize)this.Box记录).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabControl.ResumeLayout(false);
            this.Page更新.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            ((ISupportInitialize)this.Box间隔时间).EndInit();
            this.Page关于.ResumeLayout(false);
            this.Page关于.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox7.ResumeLayout(false);
            ((ISupportInitialize)this.pictureBox6).EndInit();
            this.groupBox8.ResumeLayout(false);
            this.groupBox8.PerformLayout();
            this.Page赞助.ResumeLayout(false);
            ((ISupportInitialize)this.pictureBox7).EndInit();
            this.Page反馈.ResumeLayout(false);
            this.Page反馈.PerformLayout();
            base.ResumeLayout(false);
        }
    }
}
